version: '3'
services:
  weborka:
    build: .
    depends_on:
      - dborka
    ports:
      - "8081:8081"
    volumes:
      - .:/app:Z
      - /var/run/docker.sock:/var/run/docker.sock
  dborka:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=orka
      - POSTGRES_USER=orka
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - orka-dborka-data:/var/lib/postgresql/data/pgdata
  
volumes:
  orka-dborka-data:

